services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/postgres
      DATABASE_RESET: true
      DATABASE_POPULATE: true
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  
